### ISSUE TITLE
print string format

### ISSUE THREAD

**Issue by abitofalchemy** [justinsowhat/nlp4j-wrapper#1]
in .versions ... should the return print have the following syntax: "print("{}".format(XXX)) because in Python3.6 I get `In [6]: nlp4j_wrapper.version(BINARIES_PATH)
b'========================================\nNLP4J Version 1.1.3\nContact: choi@mathcs.emory.edu\nWebpage: http://emorynlp.github.io/nlp4j\n========================================\n'` otherwise.

**Comment by abitofalchemy** [comment]
Are you still using nlp4j to build dependency graphs given a sentence/text or doc?

**Comment by justinsowhat** [comment]
Hi, sorry for the late response! 

So it was tested in Python 2, so there is not newline character in the README. However, in Python 3, there are newline characters when using the `version` function.

**Comment by justinsowhat** [comment]
@abitofalchemy I have pushed a new commit to address the string formatting issue in python 3. It should be good to go. 

And I haven't use NLP4J in years, since it was used in a side project of mine a few years ago.
